const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("mindfile", {
  getLocations: () => ipcRenderer.invoke("system:locations"),
  chooseFolder: () => ipcRenderer.invoke("dialog:choose-folder"),
  getInfo: (itemPath) => ipcRenderer.invoke("fs:info", itemPath),
  listDirectory: (itemPath, options) => ipcRenderer.invoke("fs:list", itemPath, options),
  getIcon: (itemPath) => ipcRenderer.invoke("fs:icon", itemPath),
  preview: (itemPath) => ipcRenderer.invoke("fs:preview", itemPath),
  open: (itemPath) => ipcRenderer.invoke("fs:open", itemPath),
  reveal: (itemPath) => ipcRenderer.invoke("fs:reveal", itemPath),
  properties: (itemPath) => ipcRenderer.invoke("fs:properties", itemPath),
  copyPath: (itemPath) => ipcRenderer.invoke("fs:copy-path", itemPath),
  createFolder: (parentPath, name) => ipcRenderer.invoke("fs:create-folder", parentPath, name),
  rename: (itemPath, name) => ipcRenderer.invoke("fs:rename", itemPath, name),
  chooseMoveTarget: (itemPath) => ipcRenderer.invoke("fs:choose-move-target", itemPath),
  chooseCopyTarget: (itemPath) => ipcRenderer.invoke("fs:choose-copy-target", itemPath),
  move: (itemPath, destination) => ipcRenderer.invoke("fs:move", itemPath, destination),
  copy: (itemPath, destination) => ipcRenderer.invoke("fs:copy", itemPath, destination),
  trash: (itemPath) => ipcRenderer.invoke("fs:trash", itemPath),
  undoTrash: (token) => ipcRenderer.invoke("fs:undo-trash", token),
  commitTrash: (token) => ipcRenderer.invoke("fs:commit-trash", token),
  search: (rootPath, query, filters) => ipcRenderer.invoke("fs:search", rootPath, query, filters),
  watch: (itemPath) => ipcRenderer.invoke("fs:watch", itemPath),
  unwatchAll: () => ipcRenderer.invoke("fs:unwatch-all"),
  showContextMenu: (details) => ipcRenderer.send("menu:show", details),
  onContextCommand: (callback) => ipcRenderer.on("menu:command", (_event, command) => callback(command)),
  onFileChanged: (callback) => ipcRenderer.on("fs:changed", (_event, details) => callback(details)),
});
